apiVersion: v1
kind: Service
metadata:
  name: frontend-nane-2
  namespace: online-boutique
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: frontend-nane-2
  namespace: online-boutique
