kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: external-http
  namespace: online-boutique
  annotations:
    configsync.gke.io/cluster-name-selector: "gke-cls-app-euwe-1"
spec:
  gatewayClassName: gke-l7-global-external-managed-mc
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: lb-healthcheck
  namespace: online-boutique
  annotations:
    configsync.gke.io/cluster-name-selector: "gke-cls-app-euwe-1"
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: TCP
      httpHealthCheck:
        port: 80
        requestPath: "/"
        proxyHeader: NONE
  targetRef:
    group: net.gke.io
    kind: ServiceImport
    name: frontend
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: public-store-route
  namespace: online-boutique
  labels:
    gateway: external-http
  annotations:
    configsync.gke.io/cluster-name-selector: "gke-cls-app-euwe-1"
spec:
  hostnames:
    - "store.example.com"
  parentRefs:
    - name: external-http
  rules:
    - backendRefs:
        - group: net.gke.io
          kind: ServiceImport
          name: frontend
          port: 80