apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: adservice
  namespace: online-boutique
spec:
  podSelector:
    matchLabels:
      app: adservice
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - port: 9555
          protocol: TCP
  egress:
    - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-google-health-checks-ingress
  namespace: online-boutique
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 130.211.0.0/22
        - ipBlock:
            cidr: 35.191.0.0/16
        - ipBlock:
            cidr: 35.190.0.0/16
        - ipBlock:
            cidr: 169.254.169.254/32
        - ipBlock:
            cidr: 209.85.152.0/22
        - ipBlock:
            cidr: 209.85.204.0/22
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-googleapis-egress
  namespace: online-boutique
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 130.211.0.0/22
        - ipBlock:
            cidr: 35.191.0.0/16
        - ipBlock:
            cidr: 35.190.0.0/16
        - ipBlock:
            cidr: 169.254.169.254/32
        - ipBlock:
            cidr: 209.85.152.0/22
        - ipBlock:
            cidr: 209.85.204.0/22
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 8080
